version: '3.8'

services:
  apache_php:
    build:
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=Projet1
      - MYSQL_USER=TeeDog
      - MYSQL_PASSWORD=quentin1234
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=Projet1
      - MYSQL_USER=TeeDog
      - MYSQL_PASSWORD=quentin1234
    ports:
      - 3307:3306
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  projet:


